### Site Settings ###
title               : Umang's Blog
description         : >-
                      "Can refactor a dinosaur into a chick"
baseurl             : "" #"/portfolYOU"                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : bhattumang7/bhattumang7 # bhattumang7/bhattumang7     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : bhattumang7/portfolYOU


### Plugins ###
plugins:
  - jemoji
  - jekyll-sitemap


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/fertilizer-calculator.html




### Author Info ###
author:
  name              : Umang Bhatt
  image             : Umang_Bhatt.jpg
#  behance           : your_username
# dribbble          : your_username
  email             : bhatt.umang7@gmail.com
# facebook          : ubhattu
  github            : bhattumang7
# gitlab            : your_username
#  instagram         : ubhattu
# kaggle            : your_username
  linkedin          : umangbbhatt
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : bhattumang
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
#collections:
#  projects:
#    output: true
#    permalink: /projects/:name


### Disqus ###
disqus: http-umangbhatt-in                          # Your website Shortname on disqus

### Analytics ###
analytics:
  enabled: true  # Set false to disable analytics feature
  google:
    tracking_id: UA-165903180-1

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
